### ISSUE TITLE
Unable to Join the Match. The connection is not responding.

### ISSUE THREAD

**Issue by JoeKoh27** [Ododo/scc-lan-restore#1]
I was trying to play with my friend via Radmin VPN, we get 9ms ping from each other (ping obtained from the CoopFPSUnlocker tool). We can see each other's lobbies, but when we try to join the error "Unable to Join the Match. The connection is not responding." will immediately pop up.

The output we got from sc_lan_helper.py
![image](https://github.com/Ododo/scc-lan-restore/assets/63540890/086ac8ff-bcde-4a4c-a3e2-3e5cc88fcc11)

**Comment by JoeKoh27** [comment]
Since the default MatchMakingConfig is bound to 127.0.0.1, is there a way we can change that? Or do we just edit the host file and put our iPv4 instead?

**Comment by Ododo** [comment]
Hi.
Can you provide an output of **ipconfig** ?
If it does not work even without radmin i'm thinking something in your windows network configuration is causing issues.

**Comment by Ododo** [comment]
Pushed a fix, please try with latest version of script
