### ISSUE TITLE
Doesn't do anything

### ISSUE THREAD

**Issue by DanRektLOL** [Ododo/scc-lan-restore#4]
Self-explanatory, when i go to LAN, "The Splinter Cell Conviction server is not available at this time" message pops up which is not supposed to happen. Please give help if possible

**Comment by Ododo** [comment]
Well, i can only refer you to the README.
have you followed all the instructions, especially editing the hosts file in windows ?

**Comment by DanRektLOL** [comment]
> Well, i can only refer you to the README. have you followed all the instructions, especially editing the hosts file in windows ?

No, I dont think so, I'll check. Btw, thats called a quick response what you just did

**Comment by DanRektLOL** [comment]
??

**Comment by DanRektLOL** [comment]
nvm, blacklist seems better than conviction, ill see if theres lan and nucleus on those. thx
