### ISSUE TITLE
how to add 127.0.0.1 gconnect.ubi.com

### ISSUE THREAD

**Issue by DanRektLOL** [Ododo/scc-lan-restore#6]
Am i supposed to make .sys named 127.0.0.1 gconnect.ubi.com or like do something in terminal? could use some help

**Comment by DanRektLOL** [comment]
btw i opened an issue before. (thought that the game wasnt good [based on story and fisher's personality] and closed it. but mp is different so here i am)

**Comment by Koteyka-dev** [comment]
You need to edit hosts file, what located at `C:\Windows\System32\drivers\etc`. You need to edit this file using notepad. 

1. Open notepad as administrator ([screenshot](https://imgur.com/a/f95dXEu))
2. In the end, add `127.0.0.1 gconnect.ubi.com` [screenshot](https://imgur.com/a/u9BTTVF)

Then save this file and try to run script.

**Comment by DanRektLOL** [comment]
ok, ill see
