### ISSUE TITLE
"Unable to join the match. The connection is not responding."

### ISSUE THREAD

**Issue by PIRATx3** [Ododo/scc-lan-restore#8]
so i set up the lan fix on two computers in the same network so no hamachi or tungle, just ordinary LAN. when i create a match the other pc can see it and when that pc tries to enter it cant and a message is displayed:

"Unable to join the match. The connection is not responding."

i tried this on both computers since i dont care if me or my bro is hosting but it doesnt work either way.
idk how to get around this, can someone help please?

**Comment by Ododo** [comment]
Hi @PIRATx3 .
1. when this happen try to quit match and re-host again.
2. if it still does not work, modify the python script by commenting or deleting line 20:
`# packet.payload = bytes(header) + packet.payload[196:]
`
then re-run script.

**Comment by PIRATx3** [comment]
hi, i resolved the issue by installing a different repack, if the issue appears again i will try that solution, thanks. 

the only slight inconveniences i have now is that we have to make 2 or 3 matches each before we can see each others matches, i know bout the refresh button but it doesnt help.
and the other problem is the "General protection fault" when trying to use the fps fix but idk if i'm willing to find a fix for that, since the older pc can barelly get playable framerates so it would only help me on my pc and not my bro and we probably wouldnt even play much since he isnt into these kinds of games as he says.

thank you for making this fix, this game is one of my favorites and im glad i can share the experience with my lil bro now
